name: diffusion-playground
channels:
  - xformers
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - appdirs=1.4.4
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - cryptography=39.0.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - diffusers=0.14.0
  - entrypoints=0.4
  - executing=1.2.0
  - ffmpeg=4.3
  - filelock=3.9.0
  - flit-core=3.8.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - huggingface_hub=0.13.3
  - idna=3.4
  - importlib-metadata=6.1.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.0
  - ipython=8.12.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=4.12.0
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.6.0.25
  - libcurand=10.3.2.56
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openssl=1.1.1t
  - packaging=23.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pooch=1.4.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.14.0
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.10
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0
  - pyzmq=23.2.0
  - readline=8.2
  - regex=2022.7.9
  - requests=2.28.1
  - scipy=1.10.1
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.41.1
  - stack_data=0.6.2
  - sympy=1.11.1
  - tk=8.6.12
  - tokenizers=0.11.4
  - torchaudio=2.0.0
  - torchtriton=2.0.0
  - torchvision=0.15.0
  - tornado=6.1
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - wheel=0.38.4
  - xformers=0.0.18
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.4
  - pip:
      - accelerate==0.18.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - async-timeout==4.0.2
      - attrs==22.2.0
      - contourpy==1.0.7
      - cycler==0.11.0
      - datasets==2.11.0
      - dill==0.3.6
      - einops==0.6.0
      - fonttools==4.39.3
      - frozenlist==1.3.3
      - fsspec==2023.3.0
      - ftfy==6.1.1
      - kiwisolver==1.4.4
      - matplotlib==3.7.1
      - mpmath==1.2.1
      - multidict==6.0.4
      - multiprocess==0.70.14
      - pandas==2.0.0
      - pyarrow==11.0.0
      - pyparsing==3.0.9
      - pytz==2023.3
      - responses==0.18.0
      - transformers==4.27.4
      - tzdata==2023.3
      - xxhash==3.2.0
      - yarl==1.8.2
